language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
matrix:
  allow_failures:
    - python: pypy
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: 
  - "pip install -r requirements.txt"
script: 
  - "python setup.py pytest"
